name: CI Pipeline

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # 1. Ejecutar Formateo
  Formatting:
    uses: ./.github/workflows/format.yaml

  # 2. Ejecutar Linting
  Linting:
    uses: ./.github/workflows/lint.yaml

  # 3. Ejecutar Tests (Solo si los anteriores pasaron)
  Tests:
    needs: [Formatting, Linting] # Esto los hace secuenciales
    uses: ./.github/workflows/test.yaml
#  Versions:
#    needs: [Tests] # Esto los hace secuenciales
#    uses: ./.github/workflows/version.yaml