name: Publish Github Python Package

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Vital para poder subir el paquete

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install

      - name: Build package
        run: uv build

      - name: Publish to GitHub Packages
        run: |
          uv publish \
            --publish-url https://pypi.pkg.github.com/${{ github.repository_owner }} \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }}